// BeyDeck — auto-generated by generate_data.py. Do not edit manually.
const BBX_DATA = {
  "config": {
    "budgetMax": 30,
    "cxDiscount": -2,
    "malusCombos": [
      {
        "id": "rod-160-hexa",
        "label": "WizardRod 1-60 Hexa",
        "blade": "wizardrod",
        "ratchet": "160",
        "bit": "hexa",
        "malus": 2
      },
      {
        "id": "shark-lowrush",
        "label": "SharkScale + LowRush",
        "blade": "sharkscale",
        "ratchet": null,
        "bit": "lowrush",
        "malus": 2
      },
      {
        "id": "cobalt-elevate",
        "label": "CobaltDragoon + Elevate",
        "blade": "cobaltdragoon",
        "ratchet": null,
        "bit": "elevate",
        "malus": 2
      }
    ]
  },
  "components": {
    "blade": [
      {
        "id": "stone",
        "name": "Stone",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/00/BladeStone.png/revision/latest?cb=20220219224617"
      },
      {
        "id": "destruction",
        "name": "Destruction",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f9/BladeDestruction.png/revision/latest?cb=20220103061530"
      },
      {
        "id": "dangerous",
        "name": "Dangerous",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/e6/BladeDangerous.png/revision/latest?cb=20210915033805"
      },
      {
        "id": "decay",
        "name": "Decay",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/93/BladeDecayRender.png/revision/latest?cb=20221208072927"
      },
      {
        "id": "ultimate(takaratomy)",
        "name": "Ultimate (Takara Tomy)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5b/BladeUltimate.png/revision/latest?cb=20211115060711"
      },
      {
        "id": "impactdrake",
        "name": "ImpactDrake",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/b1/BladeImpactDrake.png/revision/latest?cb=20241115024018"
      },
      {
        "id": "glory",
        "name": "Glory",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5f/BladeGloryRender.png/revision/latest?cb=20221205075102"
      },
      {
        "id": "phoenixwing",
        "name": "PhoenixWing",
        "type": "blade",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2d/BladePhoenixWing.png/revision/latest?cb=20231115091927"
      },
      {
        "id": "hellshammer",
        "name": "HellsHammer",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/67/BladeHellsHammer.png/revision/latest?cb=20240215060611"
      },
      {
        "id": "gbladedxset",
        "name": "G-Blade DX Set",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/0f/GBladeDXSet.jpeg/revision/latest?cb=20130406025242"
      },
      {
        "id": "savior",
        "name": "Savior",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/43/BladeSavior.png/revision/latest?cb=20210615063345"
      },
      {
        "id": "apocalypsebladeset",
        "name": "Apocalypse Blade Set",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/6c/ABL_Product.jpg/revision/latest?cb=20200717225520"
      },
      {
        "id": "kerbecsbladeblast",
        "name": "Kerbecs Blade Blast",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/32/BeybladeKerbecsBladeBlast.jpg/revision/latest?cb=20210415063726"
      },
      {
        "id": "devil",
        "name": "Devil",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/34/BladeDevil.png/revision/latest?cb=20210615013725"
      },
      {
        "id": "captainamerica",
        "name": "Captain America",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/8d/Captain_America_4-70GB.jpeg/revision/latest?cb=20250618034930"
      },
      {
        "id": "silverwolf",
        "name": "SilverWolf",
        "type": "blade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f1/BladeSilverWolf.png/revision/latest?cb=20240913034202"
      },
      {
        "id": "knightshield",
        "name": "KnightShield",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9c/BladeKnightShield.png/revision/latest?cb=20250609060142"
      },
      {
        "id": "dranstrike",
        "name": "DranStrike",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/67/BladeDranStrike.png/revision/latest?cb=20260313031347"
      },
      {
        "id": "shinobishadow",
        "name": "ShinobiShadow",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/48/BladeShinobiShadow.png/revision/latest?cb=20250528201917"
      },
      {
        "id": "gilded",
        "name": "Gilded",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/e5/BladeGilded.png/revision/latest?cb=20220217060532"
      },
      {
        "id": "ghostcircle",
        "name": "GhostCircle",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/7a/BladeGhostCircle.png/revision/latest?cb=20241115025132"
      },
      {
        "id": "hellsscythe",
        "name": "HellsScythe",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/e4/BladeHellsScythe.png/revision/latest?cb=20250817035337"
      },
      {
        "id": "heavensring",
        "name": "HeavensRing",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "phoenixfeather",
        "name": "PhoenixFeather",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/96/BladePhoenixFeather.png/revision/latest?cb=20231207074705"
      },
      {
        "id": "wizardarrow",
        "name": "WizardArrow",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/44/BladeWizardArrow.png/revision/latest?cb=20250626062049"
      },
      {
        "id": "guilty(takaratomy)",
        "name": "Guilty (Takara Tomy)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/46/BladeGuilty.png/revision/latest?cb=20210812041847"
      },
      {
        "id": "weisstiger",
        "name": "WeissTiger",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/37/BladeWeissTiger.png/revision/latest?cb=20240515052303"
      },
      {
        "id": "knightmail",
        "name": "KnightMail",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/fc/BladeKnightMail.png/revision/latest?cb=20241015034144"
      },
      {
        "id": "cyclone(takaratomy)",
        "name": "Cyclone (Takara Tomy)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f7/BladeCyclone.png/revision/latest?cb=20210315113321"
      },
      {
        "id": "phoenixrudder",
        "name": "PhoenixRudder",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/0f/BladePhoenixRudder.png/revision/latest?cb=20250528203411"
      },
      {
        "id": "tyrannobeat",
        "name": "TyrannoBeat",
        "type": "blade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/ff/BladeTyrannoBeat.png/revision/latest?cb=20240415173927"
      },
      {
        "id": "talonptera",
        "name": "Talon Ptera",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/ee/Quetzalcoatlus_4-55D.png/revision/latest?cb=20250808060150"
      },
      {
        "id": "devastate",
        "name": "Devastate",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5c/BladeDevastateRender.png/revision/latest?cb=20220531060500"
      },
      {
        "id": "samuraisaber",
        "name": "SamuraiSaber",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/de/BladeSamuraiSaber.png/revision/latest?cb=20241015033005"
      },
      {
        "id": "dynamite",
        "name": "Dynamite",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/cd/BladeDynamite.png/revision/latest?cb=20210315113258"
      },
      {
        "id": "unicornsting",
        "name": "UnicornSting",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/15/BladeUnicornSting.png/revision/latest?cb=20240115194629"
      },
      {
        "id": "scorpiospear",
        "name": "ScorpioSpear",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/89/BladeScorpioSpear.png/revision/latest?cb=20250614081207"
      },
      {
        "id": "knightlance",
        "name": "KnightLance",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/cb/BladeKnightLance.png/revision/latest?cb=20230808063816"
      },
      {
        "id": "vipertail",
        "name": "ViperTail",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9d/BladeViperTail.png/revision/latest?cb=20250818205656"
      },
      {
        "id": "wizardrod",
        "name": "WizardRod",
        "type": "blade",
        "tier": "GOD",
        "points": 8,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/a3/BladeWizardRod.png/revision/latest?cb=20240222003334"
      },
      {
        "id": "katana",
        "name": "Katana",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c6/BladeKatanaRender.png/revision/latest?cb=20220402045455"
      },
      {
        "id": "steelsamurai",
        "name": "Steel Samurai",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/29/SamuraiSteel_5-70GF.jpg/revision/latest?cb=20250514082453"
      },
      {
        "id": "knifeshinobi",
        "name": "Knife Shinobi",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/25/BladeKnifeShinobi.png/revision/latest?cb=20250815182407"
      },
      {
        "id": "samuraicalibur",
        "name": "SamuraiCalibur",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/ab/BladeSamuraiCalibur.png/revision/latest?cb=20250715051328"
      },
      {
        "id": "gillshark",
        "name": "Gill Shark",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3b/Gill_Shark_4-70O.jpeg/revision/latest?cb=20250820040436"
      },
      {
        "id": "sharkedge",
        "name": "SharkEdge",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2e/BladeSharkEdge.png/revision/latest?cb=20230812203549"
      },
      {
        "id": "leoncrest",
        "name": "LeonCrest",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c7/BladeLeonCrest.png/revision/latest?cb=20240712055426"
      },
      {
        "id": "shelterdrake",
        "name": "ShelterDrake",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/89/BladeShelterDrake.png/revision/latest?cb=20250530222732"
      },
      {
        "id": "vanish(takaratomy)",
        "name": "Vanish (Takara Tomy)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5c/BladeVanish.png/revision/latest?cb=20210514115222"
      },
      {
        "id": "hellschain",
        "name": "HellsChain",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/83/BladeHellsChain.png/revision/latest?cb=20250528203625"
      },
      {
        "id": "spiderman",
        "name": "Spider-Man",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/4e/Spider-Man_3-60F.jpeg/revision/latest?cb=20240729053252"
      },
      {
        "id": "sphinxcowl",
        "name": "SphinxCowl",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/31/BladeSphinxCowl.png/revision/latest?cb=20250528201304"
      },
      {
        "id": "lightningldrago(uppertype)",
        "name": "Lightning L-Drago (Upper Type)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/d0/BladeLightningL-Drago%28UpperType%29.png/revision/latest?cb=20240809163223"
      },
      {
        "id": "astral(takaratomy)",
        "name": "Astral (Takara Tomy)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9c/BladeAstral.png/revision/latest?cb=20210715041907"
      },
      {
        "id": "crimsongaruda",
        "name": "CrimsonGaruda",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/60/BladeCrimsonGaruda.png/revision/latest?cb=20241015052049"
      },
      {
        "id": "ironman",
        "name": "Iron Man",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c8/Iron_Man_4-80B.jpeg/revision/latest?cb=20240729052810"
      },
      {
        "id": "wyverngale",
        "name": "WyvernGale",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3d/BladeWyvernGale.png/revision/latest?cb=20231115091914"
      },
      {
        "id": "cobaltdrake",
        "name": "CobaltDrake",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2f/BladeCobaltDrake.png/revision/latest?cb=20250528202030"
      },
      {
        "id": "drandagger",
        "name": "DranDagger",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c8/BladeDranDagger.png/revision/latest?cb=20250528202141"
      },
      {
        "id": "magma",
        "name": "Magma",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/cc/BladeMagma.png/revision/latest?cb=20211217091830"
      },
      {
        "id": "golemrock",
        "name": "GolemRock",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/27/BladeGolemRock.png/revision/latest?cb=20250115052241"
      },
      {
        "id": "aeropegasus",
        "name": "AeroPegasus",
        "type": "blade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/58/BladeAeroPegasus.png/revision/latest?cb=20250528202546"
      },
      {
        "id": "mummycurse",
        "name": "MummyCurse",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/ab/BladeMummyCurse.png/revision/latest?cb=20251114034130"
      },
      {
        "id": "salvage",
        "name": "Salvage",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/51/BladeSalvage.png/revision/latest?cb=20220325235345"
      },
      {
        "id": "dranbuster",
        "name": "DranBuster",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/db/BladeDranBuster.png/revision/latest?cb=20250528202327"
      },
      {
        "id": "tacklegoat",
        "name": "Tackle Goat",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/cd/Tackle_Goat_2-70N.jpeg/revision/latest?cb=20250815160707"
      },
      {
        "id": "stormpegasis",
        "name": "StormPegasis",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2a/StormPegasis_3-70RA.jpeg/revision/latest?cb=20240717033658"
      },
      {
        "id": "tuskmammoth",
        "name": "Tusk Mammoth",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9c/MammothTusk_2-80E.png/revision/latest?cb=20241115015002"
      },
      {
        "id": "rhinohorn",
        "name": "RhinoHorn",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/41/BladeRhinoHorn.png/revision/latest?cb=20250528201123"
      },
      {
        "id": "hoverwyvern",
        "name": "Hover Wyvern",
        "type": "blade",
        "tier": "B",
        "points": 2,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/71/Hover_Wyvern_3-85N.jpeg/revision/latest?cb=20250612062923"
      },
      {
        "id": "roartyranno",
        "name": "Roar Tyranno",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5e/Roar_Tyranno_9-60GF.jpeg/revision/latest?cb=20241003084111"
      },
      {
        "id": "savagebear",
        "name": "Savage Bear",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/1e/BearScratch_%28BX-37%29.png/revision/latest?cb=20240913033714"
      },
      {
        "id": "sharkscale",
        "name": "SharkScale",
        "type": "blade",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/e0/BladeSharkScale.png/revision/latest?cb=20250715051433"
      },
      {
        "id": "whalewave",
        "name": "WhaleWave",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/89/BladeWhaleWave.png/revision/latest?cb=20240812022438"
      },
      {
        "id": "dransword",
        "name": "DranSword",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5f/BladeDranSword.png/revision/latest?cb=20250814202546"
      },
      {
        "id": "chewbacca",
        "name": "Chewbacca",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3f/Chewbacca_4-80LF.jpeg/revision/latest?cb=20250903053227"
      },
      {
        "id": "starscream",
        "name": "Starscream",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c1/Starscream_3-80N.jpeg/revision/latest?cb=20240514171842"
      },
      {
        "id": "blackshell",
        "name": "BlackShell",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3c/BladeBlackShell.png/revision/latest?cb=20250528201216"
      },
      {
        "id": "lightningldrago(rapidhittype)",
        "name": "Lightning L-Drago (Rapid-Hit Type)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5b/BladeLightningL-Drago%28Rapid-HitType%29.png/revision/latest?cb=20240809163229"
      },
      {
        "id": "triceraspiky",
        "name": "TriceraSpiky",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/78/BladeTriceraSpiky.png/revision/latest?cb=20260207193346"
      },
      {
        "id": "prominence(takaratomy)",
        "name": "Prominence (Takara Tomy)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/bc/BladeProminence.png/revision/latest?cb=20210915033819"
      },
      {
        "id": "gustbat",
        "name": "Gust Bat",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "roar(takaratomy)",
        "name": "Roar (Takara Tomy)",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/58/BladeRoar.png/revision/latest?cb=20210615062559"
      },
      {
        "id": "themandalorian",
        "name": "The Mandalorian",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/96/The_Mandalorian_3-60F.jpeg/revision/latest?cb=20240729052605"
      },
      {
        "id": "thanos",
        "name": "Thanos",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/af/Thanos_4-60P.jpeg/revision/latest?cb=20240729052849"
      },
      {
        "id": "redhulk",
        "name": "Red Hulk",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/ed/Red_Hulk_1-80R.jpeg/revision/latest?cb=20250618034946"
      },
      {
        "id": "xenoxcalibur",
        "name": "XenoXcalibur",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/bb/BladeXenoXcalibur.png/revision/latest?cb=20250322231907"
      },
      {
        "id": "berserk",
        "name": "Berserk",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9c/BladeBerserk.png/revision/latest?cb=20220217064900"
      },
      {
        "id": "yellkong",
        "name": "Yell Kong",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/03/Yell_Kong_3-60GB.jpeg/revision/latest?cb=20241003085621"
      },
      {
        "id": "generalgrievous",
        "name": "General Grievous",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5e/General_Grievous_3-80HN.jpeg/revision/latest?cb=20250618035039"
      },
      {
        "id": "moffgideon",
        "name": "Moff Gideon",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/6f/Moff_Gideon_3-80N.jpeg/revision/latest?cb=20240729052534"
      },
      {
        "id": "greengoblin",
        "name": "Green Goblin",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/95/Green_Goblin_9-80HT.jpeg/revision/latest?cb=20250903053921"
      },
      {
        "id": "victoryvalkyrie",
        "name": "VictoryValkyrie",
        "type": "blade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      }
    ],
    "ratchet": [
      {
        "id": "180",
        "name": "1-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/46/Ratchet1-80.png/revision/latest?cb=20240513065345"
      },
      {
        "id": "680",
        "name": "6-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 26,
        "comp_score": 0.74,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/98/Ratchet6-80.png/revision/latest?cb=20250215050704"
      },
      {
        "id": "070",
        "name": "0-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 50,
        "comp_score": 1.17,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/08/Ratchet0-70.png/revision/latest?cb=20250415034357"
      },
      {
        "id": "660",
        "name": "6-60",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/53/Ratchet6-60.png/revision/latest?cb=20250215050512"
      },
      {
        "id": "170",
        "name": "1-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f1/Ratchet1-70.png/revision/latest?cb=20250715052629"
      },
      {
        "id": "570",
        "name": "5-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 240,
        "comp_score": 0.73,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/cc/Ratchet5-70.png/revision/latest?cb=20240215060642"
      },
      {
        "id": "470",
        "name": "4-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 28,
        "comp_score": 1.5,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/16/Ratchet4-70.png/revision/latest?cb=20240524163324"
      },
      {
        "id": "080",
        "name": "0-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 60,
        "comp_score": 0.55,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/ac/Ratchet0-80.png/revision/latest?cb=20241115025146"
      },
      {
        "id": "780",
        "name": "7-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 30,
        "comp_score": 1.77,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/d7/Ratchet7-80.png/revision/latest?cb=20250115050921"
      },
      {
        "id": "450",
        "name": "4-50",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2a/Ratchet4-50.png/revision/latest?cb=20250715051521"
      },
      {
        "id": "580",
        "name": "5-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 108,
        "comp_score": 0.72,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/42/Ratchet5-80.png/revision/latest?cb=20230918165909"
      },
      {
        "id": "480",
        "name": "4-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 103,
        "comp_score": 0.34,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/ae/Ratchet4-80.png/revision/latest?cb=20250608045210"
      },
      {
        "id": "370",
        "name": "3-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/da/Ratchet3-70.png/revision/latest?cb=20240215060619"
      },
      {
        "id": "m85",
        "name": "M-85",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 29,
        "comp_score": 1.65,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/79/RatchetM-85.png/revision/latest?cb=20250515033258"
      },
      {
        "id": "455",
        "name": "4-55",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/7a/Ratchet4-55.png/revision/latest?cb=20250605000210"
      },
      {
        "id": "160",
        "name": "1-60",
        "type": "ratchet",
        "tier": "TOP",
        "points": 1,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3a/Ratchet1-60.png/revision/latest?cb=20240215060550"
      },
      {
        "id": "060",
        "name": "0-60",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 44,
        "comp_score": 1.64,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/20/Ratchet0-60.png/revision/latest?cb=20251015205044"
      },
      {
        "id": "980",
        "name": "9-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/61/Ratchet9-80.png/revision/latest?cb=20240115193705"
      },
      {
        "id": "960",
        "name": "9-60",
        "type": "ratchet",
        "tier": "TOP",
        "points": 1,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/af/Ratchet9-60.png/revision/latest?cb=20250530201949"
      },
      {
        "id": "755",
        "name": "7-55",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/af/Ratchet7-55.png/revision/latest?cb=20251114034152"
      },
      {
        "id": "970",
        "name": "9-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/86/Ratchet9-70.png/revision/latest?cb=20240712055351"
      },
      {
        "id": "380",
        "name": "3-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/69/Ratchet3-80.png/revision/latest?cb=20250609060206"
      },
      {
        "id": "360",
        "name": "3-60",
        "type": "ratchet",
        "tier": "TOP",
        "points": 1,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/1b/Ratchet3-60.png/revision/latest?cb=20240913063429"
      },
      {
        "id": "770",
        "name": "7-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/38/Ratchet7-70.png/revision/latest?cb=20241015043216"
      },
      {
        "id": "760",
        "name": "7-60",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/39/Ratchet7-60.png/revision/latest?cb=20240712055419"
      },
      {
        "id": "150",
        "name": "1-50",
        "type": "ratchet",
        "tier": "TOP",
        "points": 1,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c2/Ratchet1-50.png/revision/latest?cb=20260214040444"
      },
      {
        "id": "385",
        "name": "3-85",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 29,
        "comp_score": 2.27,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/b8/Ratchet3-85.png/revision/latest?cb=20260202220915"
      },
      {
        "id": "670",
        "name": "6-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 26,
        "comp_score": 2.16,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/14/Ratchet6-70.png/revision/latest?cb=20250715051344"
      },
      {
        "id": "965",
        "name": "9-65",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 15,
        "comp_score": 2.02,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/25/Ratchet9-65.png/revision/latest?cb=20250912034512"
      },
      {
        "id": "460",
        "name": "4-60",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 374,
        "comp_score": 0.4,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/46/Ratchet4-60.png/revision/latest?cb=20250317055414"
      },
      {
        "id": "870",
        "name": "8-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 22,
        "comp_score": 5.1,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/ca/Ratchet8-70.png/revision/latest?cb=20260214040608"
      },
      {
        "id": "280",
        "name": "2-80",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 6,
        "comp_score": 2.46,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/dc/Ratchet2-80.png/revision/latest?cb=20240527053613"
      },
      {
        "id": "270",
        "name": "2-70",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 13,
        "comp_score": 3.52,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/cb/Ratchet2-70.png/revision/latest?cb=20241015033717"
      },
      {
        "id": "260",
        "name": "2-60",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 47,
        "comp_score": 0.99,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/a6/Ratchet2-60.png/revision/latest?cb=20240614034142"
      },
      {
        "id": "560",
        "name": "5-60",
        "type": "ratchet",
        "tier": "STANDARD",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f7/Ratchet5-60.png/revision/latest?cb=20230918165846"
      }
    ],
    "bit": [
      {
        "id": "level",
        "name": "Level",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/56/BitLevel.png/revision/latest?cb=20241015033722"
      },
      {
        "id": "underneedle",
        "name": "Under Needle",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/16/BitUnderNeedle.png/revision/latest?cb=20250115052342"
      },
      {
        "id": "diskball",
        "name": "Disk Ball",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 71,
        "comp_score": 0.9,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/10/BitDiskBall.png/revision/latest?cb=20240215060650"
      },
      {
        "id": "ball",
        "name": "Ball",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/8c/BitBall.png/revision/latest?cb=20250608045235"
      },
      {
        "id": "orb",
        "name": "Orb",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/17/BitOrb.png/revision/latest?cb=20230918165916"
      },
      {
        "id": "jolt",
        "name": "Jolt",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/10/BitJolt.png/revision/latest?cb=20251114032437"
      },
      {
        "id": "zap",
        "name": "Zap",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 57,
        "comp_score": 1.67,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/61/BitZap.png/revision/latest?cb=20250415034411"
      },
      {
        "id": "underflat",
        "name": "Under Flat",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 73,
        "comp_score": 1.37,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/55/BitUnderFlat.png/revision/latest?cb=20250715051536"
      },
      {
        "id": "point",
        "name": "Point",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/bf/BitPoint.png/revision/latest?cb=20230918165854"
      },
      {
        "id": "taper",
        "name": "Taper",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/ad/BitTaper.png/revision/latest?cb=20250317055452"
      },
      {
        "id": "narrow",
        "name": "Narrow",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/d6/BitNarrow.png/revision/latest?cb=20260517043012"
      },
      {
        "id": "freeball",
        "name": "Free Ball",
        "type": "bit",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/78/BitFreeBall.png/revision/latest?cb=20240913034835"
      },
      {
        "id": "freeflat",
        "name": "Free Flat",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/b4/BitFreeFlat.png/revision/latest?cb=20260313031408"
      },
      {
        "id": "unite",
        "name": "Unite",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/a0/BitUnite.png/revision/latest?cb=20240515052315"
      },
      {
        "id": "gearball",
        "name": "Gear Ball",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/97/BitGearBall.png/revision/latest?cb=20231115091947"
      },
      {
        "id": "flat",
        "name": "Flat",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 376,
        "comp_score": 0.57,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/b0/BitFlat.png/revision/latest?cb=20240913063436"
      },
      {
        "id": "transpoint",
        "name": "Trans Point",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 36,
        "comp_score": 1.13,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/d0/BitTransPoint.png/revision/latest?cb=20241015052109"
      },
      {
        "id": "wallball",
        "name": "Wall Ball",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 67,
        "comp_score": 2.22,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/38/BitWallBall.png/revision/latest?cb=20250613042119"
      },
      {
        "id": "needle",
        "name": "Needle",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 88,
        "comp_score": 0.51,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/26/BitNeedle.png/revision/latest?cb=20250609060238"
      },
      {
        "id": "merge",
        "name": "Merge",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5e/BitMerge.png/revision/latest?cb=20250715051358"
      },
      {
        "id": "dot",
        "name": "Dot",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 56,
        "comp_score": 0.68,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/b2/BitDot.png/revision/latest?cb=20240614034756"
      },
      {
        "id": "ignition",
        "name": "Ignition",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 16,
        "comp_score": 5.63,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/37/BitIgnition.png/revision/latest?cb=20260214040456"
      },
      {
        "id": "wallwedge",
        "name": "Wall Wedge",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 10,
        "comp_score": 3.8,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9a/BitWallWedge.png/revision/latest?cb=20260115043200"
      },
      {
        "id": "transkick",
        "name": "Trans Kick",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5d/BitTransKick.png/revision/latest?cb=20250812023538"
      },
      {
        "id": "spike",
        "name": "Spike",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/7d/BitSpike.png/revision/latest?cb=20231014012757"
      },
      {
        "id": "loworb",
        "name": "Low Orb",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f4/BitLowOrb.png/revision/latest?cb=20250215050618"
      },
      {
        "id": "vortex",
        "name": "Vortex",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f9/BitVortex.png/revision/latest?cb=20250215050522"
      },
      {
        "id": "metalneedle",
        "name": "Metal Needle",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/47/BitMetalNeedle.png/revision/latest?cb=20240416003755"
      },
      {
        "id": "glide",
        "name": "Glide",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/d5/BitGlide.png/revision/latest?cb=20240712055345"
      },
      {
        "id": "yielding",
        "name": "Yielding",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 13,
        "comp_score": 7.31,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f1/BitYielding.png/revision/latest?cb=20260214043217"
      },
      {
        "id": "cyclone",
        "name": "Cyclone",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 122,
        "comp_score": 0.59,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/fb/BitCyclone.png/revision/latest?cb=20240614034151"
      },
      {
        "id": "accel",
        "name": "Accel",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/8e/BitAccel.png/revision/latest?cb=20240215060559"
      },
      {
        "id": "hightaper",
        "name": "High Taper",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 54,
        "comp_score": 0.96,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/b5/BitHighTaper.png/revision/latest?cb=20231014024512"
      },
      {
        "id": "quake",
        "name": "Quake",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/ed/BitQuake.png/revision/latest?cb=20240503184404"
      },
      {
        "id": "elevate",
        "name": "Elevate",
        "type": "bit",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/38/BitElevate.png/revision/latest?cb=20240812022551"
      },
      {
        "id": "gearneedle",
        "name": "Gear Needle",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 33,
        "comp_score": 0.86,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9d/BitGearNeedle.png/revision/latest?cb=20240116063659"
      },
      {
        "id": "rubberaccel",
        "name": "Rubber Accel",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 132,
        "comp_score": 1.38,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5a/BitRubberAccel.png/revision/latest?cb=20241015044738"
      },
      {
        "id": "hexa",
        "name": "Hexa",
        "type": "bit",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/8c/BitHexa.png/revision/latest?cb=20240215060626"
      },
      {
        "id": "gearpoint",
        "name": "Gear Point",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/36/BitGearPoint.png/revision/latest?cb=20240115194709"
      },
      {
        "id": "gearunite",
        "name": "Gear Unite",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/33/BitGearUnite.png/revision/latest?cb=20260415025452"
      },
      {
        "id": "kick",
        "name": "Kick",
        "type": "bit",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/47/BitKick.png/revision/latest?cb=20250314041641"
      },
      {
        "id": "rush",
        "name": "Rush",
        "type": "bit",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/e1/BitRush.png/revision/latest?cb=20231014022216"
      },
      {
        "id": "diskspike",
        "name": "Disk Spike",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/47/BitDiskSpike.png/revision/latest?cb=20260615070431"
      },
      {
        "id": "lowrush",
        "name": "Low Rush",
        "type": "bit",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/36/BitLowRush.png/revision/latest?cb=20241115024042"
      },
      {
        "id": "highneedle",
        "name": "High Needle",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 110,
        "comp_score": 0.38,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2f/BitHighNeedle.png/revision/latest?cb=20230808063846"
      },
      {
        "id": "wedge",
        "name": "Wedge",
        "type": "bit",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/29/BitWedge.png/revision/latest?cb=20250215050716"
      },
      {
        "id": "gearflat",
        "name": "Gear Flat",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 83,
        "comp_score": 0.94,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/bd/BitGearFlat.png/revision/latest?cb=20231115091943"
      },
      {
        "id": "lowflat",
        "name": "Low Flat",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 567,
        "comp_score": 0.55,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/0e/BitLowFlat.png/revision/latest?cb=20230812203610"
      },
      {
        "id": "gearrush",
        "name": "Gear Rush",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 15,
        "comp_score": 1.55,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/58/BitGearRush.png/revision/latest?cb=20250415032926"
      },
      {
        "id": "dranzer(bitbeast)",
        "name": "Dranzer (Bit-Beast)",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/80/Dranzer774.jpg/revision/latest?cb=20111207183011"
      },
      {
        "id": "kaneyamashita",
        "name": "Kane Yamashita",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/59/CyberDragoon2.jpg/revision/latest?cb=20100717030353"
      },
      {
        "id": "slashrigerms/it",
        "name": "Slash Riger MS/it",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "jiraiyams/it",
        "name": "Jiraiya MS/it",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "wolborgms/it",
        "name": "Wolborg MS/it",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3b/Img1707vv1.jpg/revision/latest?cb=20180215192912"
      },
      {
        "id": "advanceaverazer/it",
        "name": "Advance Averazer/it",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/14/AA1.jpg/revision/latest?cb=20131106011453"
      },
      {
        "id": "magicalapems/it",
        "name": "Magical Ape MS/it",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "advancestriker/it",
        "name": "Advance Striker/it",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c2/1AdvanceStriker.JPG/revision/latest?cb=20180215200847"
      },
      {
        "id": "steven(shadowbladers)",
        "name": "Steven (Shadow Bladers)",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/30/BeyBladeMovie31.jpg/revision/latest?cb=20110830111231"
      },
      {
        "id": "king(originalseries)",
        "name": "King (Original Series)",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/e5/Ariel1.png/revision/latest?cb=20110524021113"
      },
      {
        "id": "zagartindustries",
        "name": "Zagart Industries",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9a/Beyblade_V-Force_Team_Psykick_Movie_Arc_-_Kai_vs_Goki_360333.jpg/revision/latest?cb=20190228012544"
      },
      {
        "id": "juliafernandez",
        "name": "Julia Fernandez",
        "type": "bit",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/ef/Bey%2C_Pegasus_Theme_Bladers.jpg/revision/latest?cb=20200424100927"
      }
    ],
    "assistblade": [
      {
        "id": "bumper",
        "name": "Bumper",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/a/aa/AssistBladeBumper.png/revision/latest?cb=20250215050654"
      },
      {
        "id": "slash",
        "name": "Slash",
        "type": "assistblade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/cb/AssistBladeSlash.png/revision/latest?cb=20250215050454"
      },
      {
        "id": "turn",
        "name": "Turn",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2c/AssistBladeTurn.png/revision/latest?cb=20250314041629"
      },
      {
        "id": "charge",
        "name": "Charge",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/89/AssistBladeCharge.png/revision/latest?cb=20250314041928"
      },
      {
        "id": "vertical",
        "name": "Vertical",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/65/AssistBladeVertical.png/revision/latest?cb=20260214040558"
      },
      {
        "id": "odd",
        "name": "Odd",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/85/AssistBladeOdd.png/revision/latest?cb=20260415025441"
      },
      {
        "id": "round",
        "name": "Round",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3c/AssistBladeRound.png/revision/latest?cb=20250215050554"
      },
      {
        "id": "knuckle",
        "name": "Knuckle",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/11/AssistBladeKnuckle.png/revision/latest?cb=20260214040432"
      },
      {
        "id": "heavy",
        "name": "Heavy",
        "type": "assistblade",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/0b/AssistBladeHeavy.png/revision/latest?cb=20251015205145"
      },
      {
        "id": "free",
        "name": "Free",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/be/AssistBladeFree.png/revision/latest?cb=20251015205027"
      },
      {
        "id": "assault",
        "name": "Assault",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/24/AssistBladeAssault.png/revision/latest?cb=20250613042027"
      },
      {
        "id": "dual",
        "name": "Dual",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/22/AssistBladeDual_%28Smash_Mode%29.png/revision/latest?cb=20250918112418"
      },
      {
        "id": "massive",
        "name": "Massive",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/23/AssistBladeMassive.png/revision/latest?cb=20250613042947"
      },
      {
        "id": "wheel",
        "name": "Wheel",
        "type": "assistblade",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3d/AssistBladeWheel.png/revision/latest?cb=20250613042109"
      },
      {
        "id": "jaggy",
        "name": "Jaggy",
        "type": "assistblade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/14/AssistBladeJaggy.png/revision/latest?cb=20250415032856"
      },
      {
        "id": "erase",
        "name": "Erase",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/0c/AssistBladeErase.png/revision/latest?cb=20260214043159"
      },
      {
        "id": "zillion",
        "name": "Zillion",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/37/AssistBladeZillion.png/revision/latest?cb=20260115043035"
      },
      {
        "id": "gravity",
        "name": "Gravity",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/89/AssistBladeGravity.png/revision/latest?cb=20260615040806"
      },
      {
        "id": "emperormighthop",
        "name": "EmperorMight HOp",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/51/Beyblade_X_-_EmperorMight_HOp.png/revision/latest?cb=20251121172711"
      },
      {
        "id": "pegasusblastatr",
        "name": "PegasusBlast ATr",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/24/AssistBladeAssault.png/revision/latest?cb=20250613042027"
      },
      {
        "id": "hellsreapertop",
        "name": "HellsReaper TOp",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/47/Beyblade_X_-_HellsReaper_TOp.png/revision/latest?cb=20251228054749"
      },
      {
        "id": "glimmeringstars",
        "name": "Glimmering Stars",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c9/Glimmering_Star_PegasusBlast_1.png/revision/latest?cb=20250926225025"
      },
      {
        "id": "shootingstar",
        "name": "Shooting Star",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/da/Shooting_Star_%28Chapter_20%29.png/revision/latest?cb=20250115081910"
      },
      {
        "id": "robinkazami",
        "name": "Robin Kazami",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9b/Beyblade_X_-_Bird_Kazami_%28Remastered_Render%29.png/revision/latest?cb=20250208075446"
      },
      {
        "id": "lineshindo",
        "name": "Line Shindo",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2c/Beyblade_X_EvoBattle_-_Line_Shindo_%28Female%29_2.png/revision/latest?cb=20260123171339"
      },
      {
        "id": "multinanairo",
        "name": "Multi Nana-iro",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c3/Beyblade_X_-_Multi_Nanairo.png/revision/latest?cb=20250404095131"
      },
      {
        "id": "zombie",
        "name": "Zombie",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "specialparts",
        "name": "Special Parts",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "ginro",
        "name": "Ginro",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/1f/BBX103_Ginro%2C_Shiguru_and_Shieru_eating_ramen.png/revision/latest?cb=20251108104943"
      },
      {
        "id": "omegashiroboshi",
        "name": "Omega Shiroboshi",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f4/BBX70_Omega_holding_AeroPegasus.png/revision/latest?cb=20250813112008"
      },
      {
        "id": "bladebreakers",
        "name": "Bladebreakers",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/5/5a/09.jpg655678i4689.jpg/revision/latest?cb=20110817131109"
      },
      {
        "id": "mantadiver",
        "name": "Manta Diver",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/68/Manda_Diver_Attack_Ring.jpg/revision/latest?cb=20181123210910"
      },
      {
        "id": "blizzardorthrus",
        "name": "Blizzard Orthrus",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/7a/B1ZLf.jpg/revision/latest?cb=20181025011643"
      },
      {
        "id": "kenny",
        "name": "Kenny",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/32/Hopper_in_Water.jpg/revision/latest?cb=20110812120821"
      },
      {
        "id": "beyblade(toy)",
        "name": "Beyblade (toy)",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/09/DranSword_3-60F.png/revision/latest?cb=20230516042157"
      },
      {
        "id": "johnnymcgregor",
        "name": "Johnny McGregor",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/62/1126066803_esenrquee3.jpg/revision/latest?cb=20110826130039"
      },
      {
        "id": "mr.dickenson",
        "name": "Mr. Dickenson",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/3b/4CFEBEA3-5FE5-4B13-BB4F-1E50837494BE.png/revision/latest?cb=20201215180657"
      },
      {
        "id": "altios",
        "name": "Altios",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/ec/Bey%2C_2002_Pegasion_2_Parts_%26_Stats.png/revision/latest?cb=20191215034811"
      },
      {
        "id": "smashattack",
        "name": "Smash Attack",
        "type": "assistblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      }
    ],
    "overblade": [
      {
        "id": "peak",
        "name": "Peak",
        "type": "overblade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/01/OverBladePeak.png/revision/latest?cb=20260415025424"
      },
      {
        "id": "guard",
        "name": "Guard",
        "type": "overblade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/8b/OverBladeGuard.png/revision/latest?cb=20260214040517"
      },
      {
        "id": "outer",
        "name": "Outer",
        "type": "overblade",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/f/f2/OverBladeOuter.png/revision/latest?cb=20260517042333"
      },
      {
        "id": "break",
        "name": "Break",
        "type": "overblade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/3/38/OverBladeBreak.png/revision/latest?cb=20260214040407"
      },
      {
        "id": "flow",
        "name": "Flow",
        "type": "overblade",
        "tier": "A",
        "points": 4,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/0/00/OverBladeFlow.png/revision/latest?cb=20260214043129"
      }
    ],
    "lockchip": [
      {
        "id": "hells",
        "name": "Hells",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/7a/LockChipHells.png/revision/latest?cb=20250314041513"
      },
      {
        "id": "dran",
        "name": "Dran",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/6c/LockChipDran.png/revision/latest?cb=20250215050437"
      },
      {
        "id": "wolf",
        "name": "Wolf",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/6a/LockChipWolf.png/revision/latest?cb=20251015204952"
      },
      {
        "id": "brachio",
        "name": "Brachio",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/6d/LockChipBrachio.png/revision/latest?cb=20260517042128"
      },
      {
        "id": "perseus",
        "name": "Perseus",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/6a/LockChipPerseus.png/revision/latest?cb=20250215050629"
      },
      {
        "id": "emperor",
        "name": "Emperor",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/2/2b/LockChipEmperor.png/revision/latest?cb=20251015205115"
      },
      {
        "id": "valkyrie",
        "name": "Valkyrie",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/b4/LockChipValkyrie.png/revision/latest?cb=20250715032014"
      },
      {
        "id": "sol",
        "name": "Sol",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/6e/LockChipSol.png/revision/latest?cb=20250812023449"
      },
      {
        "id": "phoenix",
        "name": "Phoenix",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/7a/LockChipPhoenix.png/revision/latest?cb=20260115042959"
      },
      {
        "id": "leon",
        "name": "Leon",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/1/1a/LockChipLeon.png/revision/latest?cb=20250515031153"
      },
      {
        "id": "stag",
        "name": "Stag",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/d9/LockChipStag.png/revision/latest?cb=20250820214853"
      },
      {
        "id": "unicorn",
        "name": "Unicorn",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/4e/LockChipUnicorn.png/revision/latest?cb=20260415025415"
      },
      {
        "id": "wizard",
        "name": "Wizard",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/4/43/LockChipWizard.png/revision/latest?cb=20250215050531"
      },
      {
        "id": "knight",
        "name": "Knight",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/c/c2/LockChipKnight.png/revision/latest?cb=20260214040509"
      },
      {
        "id": "kraken",
        "name": "Kraken",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/d4/LockChipKraken.png/revision/latest?cb=20250820214847"
      },
      {
        "id": "fox",
        "name": "Fox",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/6/65/LockChipFox.png/revision/latest?cb=20250415032832"
      },
      {
        "id": "rhino",
        "name": "Rhino",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/d/d7/LockChipRhino.png/revision/latest?cb=20250404235409"
      },
      {
        "id": "cerberus",
        "name": "Cerberus",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/b/bd/LockChipCerberus.png/revision/latest?cb=20250613042044"
      },
      {
        "id": "pegasus",
        "name": "Pegasus",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/86/LockChipPegasus.png/revision/latest?cb=20250613042010"
      },
      {
        "id": "drake",
        "name": "Drake",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/71/LockChipDrake.png/revision/latest?cb=20260615043143"
      },
      {
        "id": "whale",
        "name": "Whale",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/7/75/LockChipWhale.png/revision/latest?cb=20250613042706"
      },
      {
        "id": "hornet",
        "name": "Hornet",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/88/LockChipHornet.png/revision/latest?cb=20250820214840"
      },
      {
        "id": "enlil",
        "name": "Enlil",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "bahamut",
        "name": "Bahamut",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/e/e4/LockChipBahamut.png/revision/latest?cb=20260214040353"
      },
      {
        "id": "ragna",
        "name": "Ragna",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/9/9b/LockChipRagna.png/revision/latest?cb=20260214043116"
      },
      {
        "id": "eva",
        "name": "Eva",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": "https://static.wikia.nocookie.net/beyblade/images/8/8a/LockChipEvaUnit-00.png/revision/latest?cb=20260321061721"
      },
      {
        "id": "glossary",
        "name": "Glossary",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "layer",
        "name": "Layer",
        "type": "lockchip",
        "tier": "S",
        "points": 6,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      },
      {
        "id": "plastic",
        "name": "Plastic",
        "type": "lockchip",
        "tier": "C",
        "points": 0,
        "usage": 0,
        "comp_score": 0.0,
        "image": null
      }
    ]
  }
};
